spring.application.name=SgOVI
spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbcUrl=jdbc:postgresql://db-aules.uji.es:5432/ei102725sdf
spring.datasource.username=ei102725sdf
spring.datasource.password=ei102725sdf
