-- Trainer table
CREATE TABLE IF NOT EXISTS Trainer (
    trainer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    occupation VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(150),
    email VARCHAR(100) NOT NULL
);

-- Activity table
CREATE TABLE IF NOT EXISTS Activity (
    activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    duration INT NOT NULL,
    location VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    trainer_id INT NOT NULL,

    FOREIGN KEY (trainer_id)
    REFERENCES Trainer(trainer_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- OvilUser table
CREATE TABLE IF NOT EXISTS OviUser (
    oviuser_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    province VARCHAR(50),
    town VARCHAR(50),
    pc VARCHAR(10),
    age INT,
    gender VARCHAR(10),

    CHECK (age >= 0)
);

-- PapPati table
CREATE TABLE IF NOT EXISTS PapPati (
    pappati_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    province VARCHAR(50),
    town VARCHAR(50),
    pc VARCHAR(10),
    age INT,
    gender VARCHAR(10),
    cvUrl VARCHAR(255),
    training VARCHAR(100),
    experience VARCHAR(50),
    experienceType VARCHAR(50),

    CHECK (age >= 0)
);

-- ParticipantList table
CREATE TABLE IF NOT EXISTS ParticipantList (
    participantList_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance BOOLEAN NOT NULL,
    attendanceUrl VARCHAR(255),

    activity_id INT NOT NULL,
    oviuser_id INT,
    pappati_id INT,

    FOREIGN KEY (activity_id)
    REFERENCES Activity(activity_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

    FOREIGN KEY (oviuser_id)
    REFERENCES OviUser(oviuser_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

    FOREIGN KEY (pappati_id)
    REFERENCES PapPati(pappati_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE

);

-- Request table
CREATE TABLE IF NOT EXISTS Request (
    request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    training VARCHAR(100),
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    experience INT,
    experienceType VARCHAR(50),
    oviuser_id INT NOT NULL,

    FOREIGN KEY (oviuser_id)
    REFERENCES OviUser(oviuser_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE

);


-- Negotiation table
CREATE TABLE IF NOT EXISTS Negotiation (
        negotiation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stateOfApproval VARCHAR(20) NOT NULL,

        request_id INT NOT NULL,
        pappati_id INT NOT NULL,

        FOREIGN KEY (request_id)
        REFERENCES Request(request_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        FOREIGN KEY (pappati_id)
        REFERENCES PapPati(pappati_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CHECK (stateOfApproval IN ('PENDING','ACCEPTED','REJECTED'))
);

-- Contract table
CREATE TABLE IF NOT EXISTS Contract (
    contract_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wage DECIMAL(8,2) NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    url VARCHAR(255) NOT NULL,
    negotiation_id INT NOT NULL,


    FOREIGN KEY (negotiation_id)
    REFERENCES Negotiation(negotiation_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

    CHECK (wage > 0),
    CHECK (endDate >= startDate)

);

-- Message table
CREATE TABLE IF NOT EXISTS Message (
    messageId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    messageDateTime TIMESTAMP NOT NULL,
    sender VARCHAR(20) NOT NULL,
    receiver VARCHAR(20) NOT NULL,

    negotiation_id INT NOT NULL,

    FOREIGN KEY (negotiation_id)
    REFERENCES Negotiation(negotiation_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE

);

