CREATE TABLE IF NOT EXISTS tecnico_ovi (
    id_tecnico      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    apellidos       VARCHAR(150) NOT NULL,
    email           VARCHAR(200) NOT NULL UNIQUE,
    telefono        VARCHAR(20)  NOT NULL,
    contrasena_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_ovi (
    id_usuario           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(100) NOT NULL,
    apellidos            VARCHAR(150) NOT NULL,
    direccion            VARCHAR(255) NOT NULL,
    provincia            VARCHAR(100) NOT NULL,
    ciudad               VARCHAR(100) NOT NULL,
    edad                 INT NOT NULL CHECK (edad >= 0),
    genero               VARCHAR(20),
    email                VARCHAR(200) NOT NULL UNIQUE,
    telefono             VARCHAR(20)  NOT NULL,
    consentimiento_rgpd   BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_consentimiento  DATE,
    id_sgovi             VARCHAR(50) NOT NULL UNIQUE,
    contrasena_hash       VARCHAR(255) NOT NULL,
    estado               VARCHAR(30) NOT NULL DEFAULT 'pendent_aprovacio'
        CHECK (estado IN ('pendent_aprovacio', 'actiu', 'inactiu')),
    id_tecnico           INT REFERENCES tecnico_ovi(id_tecnico) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Trainer table
CREATE TABLE IF NOT EXISTS trainer (
    id_trainer  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    occupation  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(150) NOT NULL,
    email       VARCHAR(200) NOT NULL UNIQUE,
    phone       VARCHAR(20) NOT NULL,
    address     VARCHAR(255) NOT NULL
);

-- Activity table
CREATE TABLE IF NOT EXISTS activity (
    id_activity INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    date        DATE NOT NULL,
    duration    INT NOT NULL,
    location    VARCHAR(255) NOT NULL,
    category    VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    id_trainer  INT REFERENCES trainer(id_trainer) ON UPDATE CASCADE ON DELETE SET NULL
);

-- OvilUser table
CREATE TABLE IF NOT EXISTS ovil_user (
    id_ovil_user INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    phone        VARCHAR(20) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    province     VARCHAR(100) NOT NULL,
    town         VARCHAR(100) NOT NULL,
    pc           VARCHAR(20) NOT NULL,
    age          INT NOT NULL,
    gender       VARCHAR(20) NOT NULL
);

-- PapPati table
CREATE TABLE IF NOT EXISTS pap_pati (
    id_pap_pati   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         VARCHAR(20) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    province      VARCHAR(100) NOT NULL,
    town          VARCHAR(100) NOT NULL,
    pc            VARCHAR(20) NOT NULL,
    age           INT NOT NULL,
    gender        VARCHAR(20) NOT NULL,
    cv_url        VARCHAR(500),
    training      VARCHAR(255),
    experience    VARCHAR(255),
    experience_type VARCHAR(100)
);

-- ParticipantList table
CREATE TABLE IF NOT EXISTS participant_list (
    id_participant_list INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance          VARCHAR(50) NOT NULL,
    attendance_url      VARCHAR(500),
    id_activity         INT REFERENCES activity(id_activity) ON UPDATE CASCADE ON DELETE CASCADE,
    id_ovil_user        INT REFERENCES ovil_user(id_ovil_user) ON UPDATE CASCADE ON DELETE CASCADE,
    id_pap_pati         INT REFERENCES pap_pati(id_pap_pati) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Request table
CREATE TABLE IF NOT EXISTS request (
    id_request    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description   VARCHAR(500) NOT NULL,
    training      VARCHAR(255) NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    experience    VARCHAR(255),
    experience_type VARCHAR(100),
    id_ovil_user  INT REFERENCES ovil_user(id_ovil_user) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Contract table
CREATE TABLE IF NOT EXISTS contract (
    id_contract INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wage        VARCHAR(100) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    url         VARCHAR(500)
);

-- Negotiation table
CREATE TABLE IF NOT EXISTS negotiation (
    id_negotiation    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_of_approval VARCHAR(100) NOT NULL,
    id_request        INT REFERENCES request(id_request) ON UPDATE CASCADE ON DELETE CASCADE,
    id_pap_pati       INT REFERENCES pap_pati(id_pap_pati) ON UPDATE CASCADE ON DELETE CASCADE,
    id_contract       INT REFERENCES contract(id_contract) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Message table
CREATE TABLE IF NOT EXISTS message (
    id_message       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       VARCHAR(100) NOT NULL UNIQUE,
    message_date_time TIMESTAMP NOT NULL,
    sender           VARCHAR(255) NOT NULL,
    receiver         VARCHAR(255) NOT NULL,
    content          VARCHAR(1000),
    id_negotiation   INT REFERENCES negotiation(id_negotiation) ON UPDATE CASCADE ON DELETE CASCADE
);

