CREATE TABLE IF NOT EXISTS tecnico_ovi (
    id_tecnico      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    apellidos       VARCHAR(150) NOT NULL,
    email           VARCHAR(200) NOT NULL UNIQUE,
    telefono        VARCHAR(20)  NOT NULL,
    contrasena_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_ovi (
    id_usuario           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(100) NOT NULL,
    apellidos            VARCHAR(150) NOT NULL,
    direccion            VARCHAR(255) NOT NULL,
    provincia            VARCHAR(100) NOT NULL,
    ciudad               VARCHAR(100) NOT NULL,
    edad                 INT NOT NULL CHECK (edad >= 0),
    genero               VARCHAR(20),
    email                VARCHAR(200) NOT NULL UNIQUE,
    telefono             VARCHAR(20)  NOT NULL,
    consentimiento_rgpd   BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_consentimiento  DATE,
    id_sgovi             VARCHAR(50) NOT NULL UNIQUE,
    contrasena_hash       VARCHAR(255) NOT NULL,
    estado               VARCHAR(30) NOT NULL DEFAULT 'pendent_aprovacio'
        CHECK (estado IN ('pendent_aprovacio', 'actiu', 'inactiu')),
    id_tecnico           INT REFERENCES tecnico_ovi(id_tecnico) ON UPDATE CASCADE ON DELETE SET NULL
);
